"language": "java"
"jdk": "oraclejdk8"
sudo: false
cache:
  directories:
  - $HOME/.m2
  - $M2_HOME
script:
  - mvn clean jacoco:prepare-agent test -U
after_success:
  - mvn jacoco:report coveralls:report