language: java
jdk: oraclejdk8
sudo: required
#services:
#  - docker
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/docker"
script:
  - ./mvnw clean jacoco:prepare-agent test -U
#  - docker run -it --name my-maven-project -v $HOME/.m2/repository:/root/.m2/repository/ -v "$PWD":/usr/src/mymaven -w /usr/src/mymaven maven:3.5-jdk-8-alpine mvn clean jacoco:prepare-agent test -Dmaven.home=/usr/share/maven -U
#  - docker run -it --name my-maven-project-systemtests -v $HOME/.m2/repository:/root/.m2/repository/ -v "$PWD":/usr/src/mymaven -w /usr/src/mymaven maven:3.5-jdk-8-alpine mvn -f java-test-helper-generator-maven-plugin-systemtests/pom.xml clean test -Dmaven.home=/usr/share/maven -U 
after_success:
  - ./mvnw jacoco:report coveralls:report