language: java
jdk: oraclejdk8
sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
  sonarcloud:
    organization: marmer-github
    token:
      secure: "iudMB0yRK+UPB58toUn1UDSSZQGt9viq2VAU9eu7e4/B12MBIO50Ur89uVlEjOll3FuNCSkrwMaKwOOn7aZnelVNw1sJ1+U4+hiQFqg6oFA4bprYkEPAzH3aBbP4oO2FuEwftPasyUy1vzDyMm1PM8QuSbT0RaYiVUrYE5O5V7n62ZzWrvxE/XtlpvMqg1vaCF+8iHNVxEJwTAVFxKOuixsrN9pQaUAXs+DxPdTHzrIKAV/FIpyJiPG/ndP0WTW7VO9gM9J04yIt8265Fa1xlk9x3yJrc90fTC0OqnjruCJmpwjzRSIWbYTivX0iYdRkRz3v3zOcTXgB3MepwIxzqWMG75eCvJX/UfUbyDLzkctU5d6bhzVfUqvzLp1lrGZAD2CgTEknh/jZlYHz7ZFXXbAHPJovbOE/0J4CrzqXGD3cikGX8Lo5NlHW4nHEDrSSp2Mky3CU1EDjbnFpp4AbdlGhExym1frJ/Nsvsz7MUZ5uEBt20i7awQme0zDPd7ZDS1VbQKl3GkmQmQ3X4rncUxgbjUgwqMCeKzfFoLuQj48GT0BJvHoXlNmwf4h3zlZsLNddc/yMufs3XlGMC5OxUjiUQAr4m/QIL8CmjI1qTV5M1gueTtH06h0BByf8a0/kWtRV9s8Cdq7xEqPMprxg9zEFkRMfwGCpoTzgPUmPfKg="
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/apache-maven-3.5.0"
  - "$HOME/.sonar/cache"
before_cache:
- rm -rfv $HOME/.m2/repository/io/github/marmer
before_install:
- export M2_HOME=$HOME/apache-maven-3.5.0
- if [ ! -d $M2_HOME/bin ]; then curl https://archive.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz
  | tar zxf - -C $HOME; fi
- export PATH=$M2_HOME/bin:$PATH
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U
script:
- mvn clean jacoco:prepare-agent package sonar:sonar -V
after_success:
- mvn jacoco:report coveralls:report -V
