"language": "java"
"jdk": "oraclejdk7"
sudo: false
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test jacoco:report
  - mvn coveralls:report
#after_success: