language: java
jdk: oraclejdk8
sudo: required
services:
  - docker
cache:
  directories:
    - "$HOME/docker"
script:
  - docker run -it --name my-maven-project -v $HOME/.m2/repository:/root/.m2/repository/ -v "$PWD":/usr/src/mymaven -w /usr/src/mymaven maven:3.5-jdk-8-alpine mvn clean jacoco:prepare-agent test -Dmaven.home=/usr/share/maven -U -X
after_success:
  - mvn jacoco:report coveralls:report