language: java
jdk: oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/apache-maven-3.5.0"
before_cache:
  - rm -rfv $HOME/.m2/repository/io/github/marmer
before_install:
  - export M2_HOME=$HOME/apache-maven-3.5.0
  - if [ ! -d $M2_HOME/bin ]; then curl https://archive.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz | tar zxf - -C $HOME; fi
  - export PATH=$M2_HOME/bin:$PATH
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U
script:
  - mvn clean jacoco:prepare-agent test -U -X -V
after_success:
  - mvn jacoco:report coveralls:report -V
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml