language: java
jdk: oraclejdk8
sudo: false
cache:
  directories:
    - "$HOME/.m2/repository"
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn clean jacoco:prepare-agent test -Dmaven.home=/usr/share/maven -U -X -V
after_success:
  - mvn jacoco:report coveralls:report -V