"language": "java"
"jdk": "oraclejdk8"
sudo: false
cache:
  directories:
  - $HOME/.m2
script:
  - mvn clean jacoco:prepare-agent test -U
after_success:
  - mvn -f java-test-helper-generator-core/pom.xml jacoco:report coveralls:report
  - mvn -f java-test-helper-generator-maven-plugin/pom.xml jacoco:report coveralls:report 
