"language": "java"
"jdk": "oraclejdk7"
sudo: false
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn clean jacoco:prepare-agent test jacoco:report coveralls:report
#after_success: