language: java
jdk: oraclejdk8
sudo: required
services:
  - docker
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/docker"
script:
  - docker run -it --name my-maven-project -v "$PWD":/usr/src/mymaven -w /usr/src/mymaven maven:3.5-jdk-8-alpine mvn clean jacoco:prepare-agent test -Dmaven.home=/usr/share/maven 
  - docker run -it --name my-maven-project mvn -f java-test-helper-generator-maven-plugin-systemtests/pom.xml clean test -Dmaven.home=/usr/share/maven 
after_success:
  - mvn jacoco:report coveralls:report